### ISSUE TITLE
혹시 사용방식중 창이 가려져있는 상태의 제어와 함께. 

### ISSUE THREAD

**Issue by ko9ma7** [EomTaeWook/DiademMacro#12]
혹시 사용방식중 창이 가려져있는 상태의 제어 또는 마우스가 직접이동하는 방식으로 (창이 가려지면 불가한 상태.)
도 매크로 작동이 가능한가요?
혹은 class dd 같은 하드웨어 신호로 바꿔주는 기능이 추가가 가능할까요?
요즘들어 녹스 블루스택 LDplayer 등의 앱플레이어를 배제하는 경우가 많이 있어서요.
혹시 기능 추가가 가능할까 하여 문의드립니다.
항상 좋은 프로그램을 제공해 주셔서 감사합니다.

**Comment by EomTaeWook** [comment]
넵 강제 이동은 가능합니다. 옵션 박스 한개 넣어서 기능 넣어보도록 하겠습니다.
항상 의견 주셔서 감사합니다.

2022년 9월 13일 (화) 오전 11:09, ko9ma7 ***@***.***>님이 작성:

**Comment by EomTaeWook** [comment]
작업을 하다보니 마우스가 직접 이동하여 클릭을 하다보니 매크로 중단 부분이 쉽게 처리가 되지 않는군요.

클릭시에 포커싱을 잃어버려서 키보드 이벤트를 받지 못하는 경우도 발생하고요.

이 부분 처리를 위해 좀 더 생각을 해봐야할 것 같습니다.


2022년 9월 16일 (금) 오전 10:04, 엄태욱 ***@***.***>님이 작성:

**Comment by EomTaeWook** [comment]
해당 기능 구현했습니다. 금주 내로 릴리즈 합니다.
