### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by eth030** [EomTaeWook/DiademMacro#13]
Hello Sensai,
Can you please make this tool for Roblox, when game crash/frozen, close game and enter game?
kind regard.

**Comment by EomTaeWook** [comment]
It's currently not possible for the macro to determine whether the game has crashed or is simply stuck in a waiting state. One way to handle this would be to create a dedicated macro specifically for this purpose, or to try to force quit the game by simulating keyboard events if there is no response after repeatedly clicking a particular button on the screen.

**Comment by eth030** [comment]
Thanks for reply

**Comment by eth030** [comment]
![grafik](https://github.com/EomTaeWook/AppPlayerMacro/assets/6024410/e2ae6964-42e0-478e-8e6b-412922e80a82)
this is how it looks when crashed, fps to 0.0

**Comment by EomTaeWook** [comment]
Would you like to set up a macro that captures a screenshot of the frame with 0.0 in the top right corner, and then use event movements to execute Roblox?
