### ISSUE TITLE
롤에서 팅김..

### ISSUE THREAD

**Issue by Lay4U** [EomTaeWook/DiademMacro#2]
무한 재접속 증상

**Comment by EomTaeWook** [comment]
무한 재접속이요? 그건 롤 문제 아닌가요?

**Comment by Lay4U** [comment]
> 무한 재접속이요? 그건 롤 문제 아닌가요?

아뇨, 이 매크로 키고 실행할때만 그럽니다.
LOL을 실행했을때 모든 프로세스를 종료시키고, 매크로와 LDPlayer가 실행중이면 롤에서 무한 재접속 문제가 발생합니다.

relaease 최신버전
3700x 2070s tuf b450m pro 

win 10 pro 1909
os build 18363.836
업데이트 최신

**Comment by EomTaeWook** [comment]
롤 클라이언트의 무한 재접속 현상은 확인했습니다.

앱 플레이어쪽 매크로는 정상적으로 작동하고 있으며 롤 재접속이 계속 되는 현상도 확인했습니다.

다만 롤 재접속 버그는 제 매크로를 사용하지 않아도 불특정 PC에서 걸리는 버그이고 

롤 클라이언트의 로그를 보지 않는 이상 매크로를 어떻게 수정할 수 있는 방법이 없습니다.

사용해주셔서 감사합니다.

**Comment by Lay4U** [comment]
> 롤 클라이언트의 무한 재접속 현상은 확인했습니다.
> 
> 앱 플레이어쪽 매크로는 정상적으로 작동하고 있으며 롤 재접속이 계속 되는 현상도 확인했습니다.
> 
> 다만 롤 재접속 버그는 제 매크로를 사용하지 않아도 불특정 PC에서 걸리는 버그이고
> 
> 롤 클라이언트의 로그를 보지 않는 이상 매크로를 어떻게 수정할 수 있는 방법이 없습니다.
> 
> 사용해주셔서 감사합니다.

감사합니다. 저만 팅기는줄 알았습니다.
매크로는 잘 사용중입니다 :)
