### ISSUE TITLE
this.baseContentView.CaptureImage(bmp); - error

### ISSUE THREAD

**Issue by Winterian** [EomTaeWook/DiademMacro#3]
BaseContentController.cs 105번째줄에 System.NullReferenceException 해서 null값이 들어가는거 같은데 어떻게 하면 될까요?

**Comment by EomTaeWook** [comment]
작업중인 소스라서 현재 코드로는 돌아가지 않습니다. 최근된 커밋을 되돌린 후 브랜치를 새로 따시면 됩니다.

2020년 12월 11일 (금) 오전 1:03, Winterian <notifications@github.com>님이 작성:

**Comment by EomTaeWook** [comment]
Null NullReferenceException 처리가 되었습니다.
