### ISSUE TITLE
Request to implement background processes 

### ISSUE THREAD

**Issue by alx2002** [EomTaeWook/DiademMacro#4]
I looked in the source for "SelectProcess" nowhere does it truly define where the true declaration for the process list... I would like to implement to attach to background process. Are you able to share the whole source as in another solution file. 

I know background processes  aren't able to produce images in a typical instance, however the process I am running runs in the background.

**Comment by EomTaeWook** [comment]
MainWindowImpl.cs -> Refresh

_processes = Process.GetProcesses().Where(r=>r.MainWindowHandle != IntPtr.Zero)
                                                .Select(r => new KeyValuePair<string, Process>($"{r.ProcessName}", r))
                                                .OrderBy(r=>r.Key).ToArray();
                                                
The part that reads the currently running process is MainWindowImpl.cs
It exists in the Refresh function.

If you run the desired program after executing the macro, it may not be in the list.
Then click the Refresh button.
