### ISSUE TITLE
(fixed)Image canvas stays "white" blank no matter what process

### ISSUE THREAD

**Issue by alx2002** [EomTaeWook/DiademMacro#5]
**Image canvas stays "white" blank**

**The snip function still works, despite this.**

This is really odd, as it was functioning as expected earlier I was running the Macro.exe for hours.

 None of the process that were tested on were minimized or hidden.

Not sure if this matter but I am going to put it out there.
Processor	AMD Athlon Silver 3050U with Radeon Graphics      2.30 GHz
Windows 10 H 19044.1466

Not sure how to reproduce or debug this but I have tried with multiple processes all show up as blank.

Things tried:
Refreshing the processes
Running as Administrator

**Comment by alx2002** [comment]
Ok solved! the fix is Patcher need to be run as admin before anything Also

AND YOU must have some image before it will display anything, before you press start. Would be good to inform the user of this.

**Comment by EomTaeWook** [comment]
I'm glad your problem was solved.I'm glad your problem was solved.

Thank you for using the macro.Thank you for using the macro.

2022년 1월 14일 (금) 오전 7:45, Alex ***@***.***>님이 작성:
