### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alx2002** [EomTaeWook/DiademMacro#6]
Synchronous image scanning would be pretty cool.

How this would benefit? 

- Reduce search time for lengthy image scans over 50 images. 

I know you can sort of "mimic" this a little bit by copy to same content and place between images but maybe it would be better? Example: search for a certain image every 5 seconds. While it does this it would also continue following the order of things.  Maybe even establish some  "hierarchy" priority. That it would override the order into the image that is found with the "synchronous" scan.

What I mean by "synchronous" is some option alongside an image that would constantly scan for this image. As of now it follows a "next" or order that it continues to the next image until if finds it.

**Comment by EomTaeWook** [comment]
I'm not good at English, so I'm reading it with a translator.

Do you want to wait until an image is found, rather than searching in order?

**Comment by alx2002** [comment]
Sure I guess so, multiple macro process solves this  with until there is no search result is also an alternative

**Comment by EomTaeWook** [comment]
You can wait if you create a tree structure by putting the image you want to find under the dummy image by dragging the mouse.
