### ISSUE TITLE
Feature request KEYBOARD EVENT

### ISSUE THREAD

**Issue by alx2002** [EomTaeWook/DiademMacro#7]
For keyboard data event : the keyboard press key

how can I emulate space character in the text because now it doesn’t parse spaces or lines example: “        “ or maybe even unicode character lines like this below
“
            .
            .

            .
“

Where would I need to go in the file edit then to parse correctly?

**Comment by EomTaeWook** [comment]
Utils Solutions -> Infrastructure ->KeyCode.cs and InputStruct.cs

you'd better check
