### ISSUE TITLE
Feature Request regard search

### ISSUE THREAD

**Issue by alx2002** [EomTaeWook/DiademMacro#8]
Make for  image to be only searching in a certain LIMITED area not all screen -  x,y - x,y - x,y - x,y (BOX style) , manually input these x,y.  a rectangle box only search in area of the certain pixels and search from bottom pixel x to top pixel of x so searches become faster and more efficient as certain tasks require speed.

**Comment by EomTaeWook** [comment]
Display Region of Interest (ROI) within the image
work is scheduled.

The macro project has a large amount of work, so it is not possible to work at the moment.
